# Generated by Django 4.1.1 on 2022-09-21 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_answer_date_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date_updated',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Last_Updated'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='date_updated',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Last_Updated'),
        ),
    ]
